baseURL = 'http://example.org/'
copyright = '© PBJ'
languageCode = 'en-us'
title = 'PBJ Writes'
timezone = 'America/Los_Angeles'
theme = 'paige'
titlecasestyle = "Go"
enablerobotstxt = true

[outputs]
home = ["html", "json", "rss"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "mystory"
name = "My Story"
url = "/mystory/"
weight = 20

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 10

[[languages.en.menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 20

[languages.en.menu.main.params.paige]
divider_below = true