baseURL = 'https://pbjwrites.info'
copyright = '© PBJ'
languageCode = 'en-us'
title = 'PBJ Writes'
timezone = 'America/Los_Angeles'
theme = 'paige'
titlecasestyle = "Go"
enablerobotstxt = true

[outputs]
home = ["html", "json", "rss"]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "mystory"
name = "My Story"
url = "/mystory/"
weight = 20

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "pbjtheathlete"
name = "PBJ the Athlete"
parent ="mystory"
url = "/mystory/pbj_the_athlete"
weight = 22

[[languages.en.menu.main]]
identifier = "pbjtheprofessional"
name = "PBJ the Professional"
parent ="mystory"
url = "/mystory/pbj_the_professional"
weight = 21

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 10

[[languages.en.menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 14

[[languages.en.menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio/"
weight = 14

[[languages.en.menu.main]]
identifier = "templates"
name = "Templates"
parent = "portfolio"
url = "/portfolio/word_templates/"
weight = 15

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "how-to"
name = "How-to"
parent = "portfolio"
url = "/portfolio/how-to/"
weight = 16

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "video_instructions"
name = "Video Instructions"
parent = "portfolio"
url = "/portfolio/video_instructions/"
weight = 17

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "editing_samples"
name = "Editing Samples"
parent = "portfolio"
url = "/portfolio/editing_samples/"
weight = 18

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "diagram_samples"
name = "Diagram Samples"
parent = "portfolio"
url = "/portfolio/diagram_samples/"
weight = 19

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "style_guide_sample"
name = "Style Guide Sample"
parent = "portfolio"
url = "/portfolio/style_guide_sample/"
weight = 20

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 21

[taxonomies]
series = "series"
